server:
  port: 8222
  servlet:
    context-path: /api

spring:
  application:
    name: yun-picture-backend
    #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yun_pi
    username: root
    password: 1234
  profiles:
    active: local

# 接口文档
knife4j:
  enable: true
  openapi:
    title: 海龟汤接口文档
    url: https://docs.xiaominfo.com
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.vix.haiguitang.controller

#ai:
#  apiKey:
